PROMPT Upgrading database objects...
@@dbm_objects.sql
PROMPT Upgrading Package Spec DBM_UTILITY_VAR...
@@DBM_UTILITY_VAR.pks
PROMPT Upgrading Package Spec DBM_UTILITY_KRN...
@@DBM_UTILITY_KRN.pks
PROMPT Upgrading Package Body DBM_UTILITY_KRN...
@@DBM_UTILITY_KRN.pkb
show errors