
/* file generated via excel utility */
PROMPT starting modification 5
Prompt Table DPP_OPTION_ALLOWED_VALUES

Prompt Insert of row #33
INSERT INTO dpp_option_allowed_values ( 
   OTN_NAME, OAV_VALUE, DATE_CREAT, DATE_MODIF, USER_CREAT, USER_MODIF
) VALUES ( 'COMPRESSION' , 'DATA_ONLY' , SYSDATE , SYSDATE , USER , USER
);

Prompt Insert of row #34
INSERT INTO dpp_option_allowed_values ( 
   OTN_NAME, OAV_VALUE, DATE_CREAT, DATE_MODIF, USER_CREAT, USER_MODIF
) VALUES ( 'COMPRESSION' , 'METADATA_ONLY' , SYSDATE , SYSDATE , USER , USER
);
Prompt Insert of row #35
INSERT INTO dpp_option_allowed_values ( 
   OTN_NAME, OAV_VALUE, DATE_CREAT, DATE_MODIF, USER_CREAT, USER_MODIF
) VALUES ( 'COMPRESSION' , 'ALL' , SYSDATE , SYSDATE , USER , USER
);
Prompt Insert of row #36
INSERT INTO dpp_option_allowed_values ( 
   OTN_NAME, OAV_VALUE, DATE_CREAT, DATE_MODIF, USER_CREAT, USER_MODIF
) VALUES ( 'COMPRESSION' , 'NONE' , SYSDATE , SYSDATE , USER , USER
);

Prompt Insert of row #37
INSERT INTO dpp_option_allowed_values ( 
   OTN_NAME, OAV_VALUE, DATE_CREAT, DATE_MODIF, USER_CREAT, USER_MODIF
) VALUES ( 'COMPRESSION_ALGORITHM' , 'BASIC' , SYSDATE , SYSDATE , USER , USER
);

Prompt Insert of row #38
INSERT INTO dpp_option_allowed_values ( 
   OTN_NAME, OAV_VALUE, DATE_CREAT, DATE_MODIF, USER_CREAT, USER_MODIF
) VALUES ( 'COMPRESSION_ALGORITHM' , 'LOW' , SYSDATE , SYSDATE , USER , USER
);
Prompt Insert of row #39
INSERT INTO dpp_option_allowed_values ( 
   OTN_NAME, OAV_VALUE, DATE_CREAT, DATE_MODIF, USER_CREAT, USER_MODIF
) VALUES ( 'COMPRESSION_ALGORITHM' , 'MEDIUM' , SYSDATE , SYSDATE , USER , USER
);
Prompt Insert of row #40
INSERT INTO dpp_option_allowed_values ( 
   OTN_NAME, OAV_VALUE, DATE_CREAT, DATE_MODIF, USER_CREAT, USER_MODIF
) VALUES ( 'COMPRESSION_ALGORITHM' , 'HIGH' , SYSDATE , SYSDATE , USER , USER
);

Prompt Insert of row #41
INSERT INTO dpp_option_allowed_values ( 
   OTN_NAME, OAV_VALUE, DATE_CREAT, DATE_MODIF, USER_CREAT, USER_MODIF
) VALUES ( 'ENCRYPTION' , 'ALL' , SYSDATE , SYSDATE , USER , USER
);
Prompt Insert of row #42
INSERT INTO dpp_option_allowed_values ( 
   OTN_NAME, OAV_VALUE, DATE_CREAT, DATE_MODIF, USER_CREAT, USER_MODIF
) VALUES ( 'ENCRYPTION' , 'DATA_ONLY' , SYSDATE , SYSDATE , USER , USER
);
Prompt Insert of row #43
INSERT INTO dpp_option_allowed_values ( 
   OTN_NAME, OAV_VALUE, DATE_CREAT, DATE_MODIF, USER_CREAT, USER_MODIF
) VALUES ( 'ENCRYPTION' , 'ENCRYPTED_COLUMNS_ONLY' , SYSDATE , SYSDATE , USER , USER
);
Prompt Insert of row #44
INSERT INTO dpp_option_allowed_values ( 
   OTN_NAME, OAV_VALUE, DATE_CREAT, DATE_MODIF, USER_CREAT, USER_MODIF
) VALUES ( 'ENCRYPTION' , 'METADATA_ONLY' , SYSDATE , SYSDATE , USER , USER
);
Prompt Insert of row #45
INSERT INTO dpp_option_allowed_values ( 
   OTN_NAME, OAV_VALUE, DATE_CREAT, DATE_MODIF, USER_CREAT, USER_MODIF
) VALUES ( 'ENCRYPTION' , 'NONE' , SYSDATE , SYSDATE , USER , USER
);

Prompt Insert of row #46
INSERT INTO dpp_option_allowed_values ( 
   OTN_NAME, OAV_VALUE, DATE_CREAT, DATE_MODIF, USER_CREAT, USER_MODIF
) VALUES ( 'ENCRYPTION_MODE' , 'PASSWORD' , SYSDATE , SYSDATE , USER , USER
);
Prompt Insert of row #47
INSERT INTO dpp_option_allowed_values ( 
   OTN_NAME, OAV_VALUE, DATE_CREAT, DATE_MODIF, USER_CREAT, USER_MODIF
) VALUES ( 'ENCRYPTION_MODE' , 'TRANSPARENT' , SYSDATE , SYSDATE , USER , USER
);
Prompt Insert of row #48
INSERT INTO dpp_option_allowed_values ( 
   OTN_NAME, OAV_VALUE, DATE_CREAT, DATE_MODIF, USER_CREAT, USER_MODIF
) VALUES ( 'ENCRYPTION_MODE' , 'DUAL' , SYSDATE , SYSDATE , USER , USER
);

Prompt Insert of row #49
INSERT INTO dpp_option_allowed_values ( 
   OTN_NAME, OAV_VALUE, DATE_CREAT, DATE_MODIF, USER_CREAT, USER_MODIF
) VALUES ( 'LOGTIME' , 'NONE' , SYSDATE , SYSDATE , USER , USER
);
Prompt Insert of row #50
INSERT INTO dpp_option_allowed_values ( 
   OTN_NAME, OAV_VALUE, DATE_CREAT, DATE_MODIF, USER_CREAT, USER_MODIF
) VALUES ( 'LOGTIME' , 'STATUS' , SYSDATE , SYSDATE , USER , USER
);
Prompt Insert of row #51
INSERT INTO dpp_option_allowed_values ( 
   OTN_NAME, OAV_VALUE, DATE_CREAT, DATE_MODIF, USER_CREAT, USER_MODIF
) VALUES ( 'LOGTIME' , 'LOGFILE' , SYSDATE , SYSDATE , USER , USER
);
Prompt Insert of row #52
INSERT INTO dpp_option_allowed_values ( 
   OTN_NAME, OAV_VALUE, DATE_CREAT, DATE_MODIF, USER_CREAT, USER_MODIF
) VALUES ( 'LOGTIME' , 'ALL' , SYSDATE , SYSDATE , USER , USER
);
