set define off
set define on
PROMPT Creating database objects...
@@ds_objects
set define off
PROMPT Creating package and type specifications...
PROMPT Installing DS_READ_CSV_CLOB type spec...
@@DS_READ_CSV_CLOB.tps
show error
PROMPT Installing DS_CRYPTO_VAR package spec...
@@DS_CRYPTO_VAR.pks
show error
PROMPT Installing DS_CRYPTO_KRN package spec...
@@DS_CRYPTO_KRN.pks
show error
PROMPT Installing DS_UTILITY_VAR package spec...
@@DS_UTILITY_VAR.pks
show error
PROMPT Installing DS_MASKER_KRN package spec...
@@DS_MASKER_KRN.pks
show error
PROMPT Installing DS_UTILITY_KRN package spec...
@@DS_UTILITY_KRN.pks
show error
PROMPT Installing DS_UTILITY_EXT package spec...
@@DS_UTILITY_EXT.pks
show error
@@DS_UTILITY_LIC.pks
PROMPT Installing DS_UTILITY_LIC package spec...
show error
PROMPT Creating package and type bodies...
PROMPT Installing DS_READ_CSV_CLOB type body...
@@DS_READ_CSV_CLOB.tpb
show error
PROMPT Installing DS_CRYPTO_KRN package body...
@@DS_CRYPTO_KRN.pkb
show error
PROMPT Installing DS_MASKER_KRN package body...
@@DS_MASKER_KRN.pkb
show error
PROMPT Installing DS_UTILITY_KRN package body...
@@DS_UTILITY_KRN.pkb
show error
PROMPT Installing DS_UTILITY_EXT package body...
@@DS_UTILITY_EXT.pkb
show error
PROMPT Creating data sets...
@@ds_EU6_FAMILY_NAMES_217.sql
@@ds_EU_MAJOR_CITIES_590.sql
@@ds_INT_COUNTRIES_250.sql
@@ds_INT_CURRENCIES_170.sql
@@ds_INT_GIVEN_NAMES_250.sql
@@ds_FOOD.sql
@@ds_COLORS.sql
@@ds_OBJECTS_200.sql
@@ds_EU_COUNTRIES_27.sql
PROMPT Creating sensitive data patterns...
@@ds_patterns.sql
