PROMPT Installing database objects...
@@dbm_objects.sql
PROMPT Installing Package DBM_UTILITY_VAR...
@@DBM_UTILITY_VAR.pks
show errors
PROMPT Installing Package DBM_UTILITY_KRN...
@@DBM_UTILITY_KRN.pks
show errors
PROMPT Installing Package Body DBM_UTILITY_KRN...
@@DBM_UTILITY_KRN.pkb
show errors