set define off
set define on
PROMPT Creating database objects...
@@doc_objects.sql
set define off
PROMPT Creating package specifications...
PROMPT Creating DOC_UTILITY package
@@DOC_UTILITY.pks
PROMPT Creating DOC_UTILITY_VAR package...
@@DOC_UTILITY_VAR.pks
PROMPT Creating DOC_UTILITY_EXT_TPL package...
@@DOC_UTILITY_EXT_TPL.pks
PROMPT Creating DOC_UTILITY_LIC package...
@@DOC_UTILITY_LIC.pks
PROMPT Creating package bodies...
PROMPT Creating DOC_UTILITY_EXT_TPL package body...
@@DOC_UTILITY_EXT_TPL.pkb
PROMPT Generating DOC_UTILITY_EXT package body...
@@doc_generate.sql
PROMPT Creating DOC_UTILITY package body...
@@DOC_UTILITY.pkb
PROMPT Creating DOC_UTILITY_VAR package body
@@DOC_UTILITY_VAR.pkb
@@doc_recompile.sql
