PROMPT Upgrading package specs...
PROMPT Upgrading package spec QC_UTILITY_LIC...
@@QC_UTILITY_LIC.pks
PROMPT Upgrading package spec QC_UTILITY_STAT...
@@QC_UTILITY_STAT.pks
PROMPT Upgrading package spec QC_UTILITY_MSG...
@@QC_UTILITY_MSG.pks
PROMPT Upgrading package spec QC_UTILITY_ORA_04068...
@@QC_UTILITY_ORA_04068.pks
PROMPT Upgrading package spec QC_UTILITY_VAR...
@@QC_UTILITY_VAR.pks
PROMPT Upgrading package spec QC_UTILITY_KRN...
@@QC_UTILITY_KRN.pks
PROMPT Upgrading package bodies...
PROMPT Upgrading package spec QC_UTILITY_KRN...
@@QC_UTILITY_KRN.pkb
PROMPT Recompiling invalid objects...
@@recompile_invalid_objects.sql