DECLARE
   my_clob CLOB;
   l_set_id ds_data_sets.set_id%TYPE;
BEGIN
   dbms_lob.createtemporary(my_clob, true);
   dbms_lob.append(my_clob,
'GIVEN_NAME_UTF8	GIVEN_NAME_ASCII	GENDER
C(16)	C(16)	C(1)
Robert	Robert	M
James	James	M
John	John	M
David	David	M
Michael	Michael	M
William	William	M
Mary	Mary	F
Marie	Marie	F
Maria	Maria	F
Joseph	Joseph	M
Thomas	Thomas	M
Daniel	Daniel	M
Jean	Jean	M
Richard	Richard	M
Charles	Charles	M
Paul	Paul	M
Patricia	Patricia	F
Christopher	Christopher	M
Barbara	Barbara	F
Linda	Linda	F
Patrick	Patrick	M
Anna	Anna	F
Anthony	Anthony	M
Jennifer	Jennifer	F
Sarah	Sarah	F
Matthew	Matthew	M
Elizabeth	Elizabeth	F
Kevin	Kevin	M
Laura	Laura	F
Eric	Eric	M
Steven	Steven	M
George	George	M
Mark	Mark	M
Michel	Michel	M
Peter	Peter	M
Sandra	Sandra	F
Donald	Donald	M
Jessica	Jessica	F
Christian	Christian	M
Christine	Christine	F
Nicole	Nicole	F
Edward	Edward	M
Kenneth	Kenneth	F
Andrew	Andrew	M
Pierre	Pierre	M
Joshua	Joshua	M
Catherine	Catherine	F
Roger	Roger	M
Margaret	Margaret	F
Anne	Anne	F
Lisa	Lisa	F
Nancy	Nancy	F
Brian	Brian	M
Louis	Louis	M
Marc	Marc	M
André	Andre	M
Benjamin	Benjamin	M
Raymond	Raymond	M
Jonathan	Jonathan	M
Jacqueline	Jacqueline	F
Jose	Jose	M
Susan	Susan	F
Ronald	Ronald	M
Karen	Karen	F
Frank	Frank	M
Jason	Jason	M
Timothy	Timothy	M
Dorothy	Dorothy	M
Samuel	Samuel	M
Emma	Emma	F
Julie	Julie	F
Michelle	Michelle	F
Helen	Helen	F
Betty	Betty	F
Ryan	Ryan	M
Antonio	Antonio	M
Philippe	Philippe	M
Alexander	Alexander	M
Jeffrey	Jeffrey	M
Monique	Monique	F
Alice	Alice	M
Albert	Albert	M
Angela	Angela	F
Emily	Emily	M
Jacob	Jacob	M
Ruth	Ruth	M
Gary	Gary	M
Nicholas	Nicholas	M
Stephen	Stephen	M
Manuel	Manuel	M
Nicolas	Nicolas	M
Martin	Martin	M
Sara	Sara	F
Jeanne	Jeanne	F
Melissa	Melissa	F
Julia	Julia	F
Bernard	Bernard	M
Walter	Walter	M
Ashley	Ashley	M
Alain	Alain	M
Rebecca	Rebecca	F
Amanda	Amanda	F
Marcel	Marcel	M
Kimberly	Kimberly	F
Nathalie	Nathalie	F
Denise	Denise	F
Gregory	Gregory	M
Stephanie	Stephanie	F
Jack	Jack	M
Donna	Donna	F
Isabelle	Isabelle	F
Carol	Carol	F
Annie	Annie	F
Jacques	Jacques	M
Vincent	Vincent	M
Kathleen	Kathleen	F
Scott	Scott	M
Deborah	Deborah	M
Justin	Justin	M
Louise	Louise	F
Dominique	Dominique	F
Marija	Marija	F
Eva	Eva	F
Arthur	Arthur	M
Larry	Larry	M
Charlotte	Charlotte	F
Nathan	Nathan	M
Adam	Adam	M
Jan	Jan	M
Martine	Martine	F
Brandon	Brandon	M
Ana	Ana	F
Amy	Amy	F
Ann	Ann	F
René	Rene	M
Cynthia	Cynthia	F
Andrea	Andrea	F
Sharon	Sharon	F
Juan	Juan	M
Sophie	Sophie	F
Claude	Claude	M
Rita	Rita	F
Victor	Victor	M
Rachel	Rachel	F
Kelly	Kelly	F
Shirley	Shirley	M
Virginia	Virginia	F
François	Francois	M
Aaron	Aaron	M
Henry	Henry	M
Christophe	Christophe	M
Danielle	Danielle	F
Gabriel	Gabriel	M
Caroline	Caroline	F
Dennis	Dennis	M
Martha	Martha	F
Francisco	Francisco	M
Victoria	Victoria	F
Suzanne	Suzanne	F
Maria carmen	Maria carmen	F
Francis	Francis	M
Guy	Guy	M
Christiane	Christiane	F
Katherine	Katherine	F
Paula	Paula	F
Elisabeth	Elisabeth	M
Brenda	Brenda	F
Françoise	Francoise	F
Carmen	Carmen	F
Carlos	Carlos	M
Luc	Luc	M
Rose	Rose	F
Georges	Georges	M
Jerry	Jerry	M
Jordan	Jordan	M
Christina	Christina	F
Ivan	Ivan	M
Pamela	Pamela	F
Tyler	Tyler	M
Henri	Henri	M
Diane	Diane	F
Samantha	Samantha	F
Julien	Julien	M
Lucas	Lucas	M
Maurice	Maurice	M
Alexis	Alexis	M
Frances	Frances	M
Tom	Tom	M
Olivia	Olivia	F
Olivier	Olivier	M
Pascal	Pascal	M
Willie	Willie	M
Yvonne	Yvonne	F
Florence	Florence	F
Jeremy	Jeremy	M
Carl	Carl	M
Douglas	Douglas	M
Janet	Janet	F
Teresa	Teresa	F
Irene	Irene	F
Carolyn	Carolyn	M
Harold	Harold	M
Joan	Joan	M
Debra	Debra	F
Lauren	Lauren	M
Frédéric	Frederic	M
Evelyn	Evelyn	F
Heather	Heather	M
Judith	Judith	F
Clara	Clara	F
Doris	Doris	M
Dylan	Dylan	M
Robin	Robin	M
Vanessa	Vanessa	F
Joyce	Joyce	M
Hannah	Hannah	F
Harry	Harry	M
Laurent	Laurent	M
Angel	Angel	M
Brigitte	Brigitte	F
Sylvie	Sylvie	F
Alexandra	Alexandra	F
Zachary	Zachary	M
Grace	Grace	F
Jeannine	Jeannine	F
Chantal	Chantal	M
Megan	Megan	M
Terry	Terry	M
Kyle	Kyle	M
Anita	Anita	F
Cindy	Cindy	F
Diana	Diana	F
Luis	Luis	M
Simon	Simon	M
Pauline	Pauline	F
Noah	Noah	M
Ethan	Ethan	M
Thierry	Thierry	M
Mohamed	Mohamed	M
Jesus	Jesus	M
Rosa	Rosa	F
Gloria	Gloria	F
Gerald	Gerald	M
Joe	Joe	M
Sébastien	Sebastien	M
Alexandre	Alexandre	M
Bruno	Bruno	M
Audrey	Audrey	M
Véronique	Veronique	F');
   l_set_id := ds_utility_krn.create_or_replace_data_set_def(p_set_name=>'INT_GIVEN_NAMES_250', p_set_type=>'CSV', p_params=>my_clob);
   UPDATE ds_data_sets
      SET col_names_row = 1  -- column names at row 1
        , col_types_row = 2  -- column types at row 2
        , col_sep_char = CHR(9) -- column separator is TAB
    WHERE set_id = l_set_id
   ;
   COMMIT;
   dbms_lob.freetemporary(my_clob);
END;
/
